#!/bin/sh
#
#
# Hetzner Failover for Opnestack
#
# Description:  Manages the Hetzner Failover IP mover for Openstack
#
# Authors:      Alessandro Tagliapietra
#
# Website:      http://www.alexnetwork.it/
#
# Support:      Twitter: @4l3x88
# License:      Apache Software License (ASL) 2.0
#
#
# See usage() function below for more details ...
#
# OCF instance parameters:
#   OCF_RESKEY_binary
#######################################################################
# Initialization:

: ${OCF_FUNCTIONS_DIR=${OCF_ROOT}/lib/heartbeat}
. ${OCF_FUNCTIONS_DIR}/ocf-shellfuncs

#######################################################################

# Fill in some defaults if no values are specified

OCF_RESKEY_binary_default="/root/openstack_hetzner_failoverIP.py"
OCF_RESKEY_user_default="root"
OCF_RESKEY_pid_default="$HA_RSCTMP/$OCF_RESOURCE_INSTANCE.pid"

: ${OCF_RESKEY_binary=${OCF_RESKEY_binary_default}}
: ${OCF_RESKEY_user=${OCF_RESKEY_user_default}}
: ${OCF_RESKEY_pid=${OCF_RESKEY_pid_default}}

#######################################################################

usage() {
    cat <<UEND
        usage: $0 (start|stop|validate-all|meta-data|status|monitor)

        $0 manages the Hetzner Failover IP mover for Openstack as an HA resource

        The 'start' operation starts the service.
        The 'stop' operation stops the service.
        The 'validate-all' operation reports whether the parameters are valid
        The 'meta-data' operation reports this RA's meta-data information
        The 'status' operation reports whether the service is running
        The 'monitor' operation reports whether the service seems to be working

UEND
}

meta_data() {
    cat <<END
<?xml version="1.0"?>
<!DOCTYPE resource-agent SYSTEM "ra-api-1.dtd">
<resource-agent name="hetzner-failover-ip">
<version>1.0</version>

<longdesc lang="en">
Resource agent for the Hetzner Failover IP mover for Openstack
</longdesc>
<shortdesc lang="en">Manages the Hetzner Failover IP mover for Openstack</shortdesc>
<parameters>

<parameter name="binary" unique="0" required="0">
<longdesc lang="en">
Location of the Hetzner Failover IP mover for Openstack binary
</longdesc>
<shortdesc lang="en">Hetzner Failover IP mover for Openstack binary</shortdesc>
<content type="string" default="${OCF_RESKEY_binary_default}" />
</parameter>

<parameter name="user" unique="0" required="0">
<longdesc lang="en">
User running Hetzner Failover IP mover for Openstack
</longdesc>
<shortdesc lang="en">Hetzner Failover IP mover for Openstack user</shortdesc>
<content type="string" default="${OCF_RESKEY_user_default}" />
</parameter>

<parameter name="pid" unique="0" required="0">
<longdesc lang="en">
The pid file to use for this Hetzner Failover IP mover for Openstack instance
</longdesc>
<shortdesc lang="en">Hetzner Failover IP mover for Openstack pid file</shortdesc>
<content type="string" default="${OCF_RESKEY_pid_default}" />
</parameter>

</parameters>

<actions>
<action name="start" timeout="10" />
<action name="stop" timeout="10" />
<action name="status" timeout="10" />
<action name="monitor" timeout="5" interval="10" />
<action name="validate-all" timeout="5" />
<action name="meta-data" timeout="5" />
</actions>
</resource-agent>
END
}

#######################################################################
# Functions invoked by resource manager actions

hetzner_failover_ip_validate() {
    local rc

    check_binary $OCF_RESKEY_binary

    getent passwd $OCF_RESKEY_user >/dev/null 2>&1
    rc=$?
    if [ $rc -ne 0 ]; then
        ocf_log err "User $OCF_RESKEY_user doesn't exist"
        return $OCF_ERR_INSTALLED
    fi

    true
}

hetzner_failover_ip_status() {
    local pid
    local rc

    if [ ! -f $OCF_RESKEY_pid ]; then
        ocf_log info "Hetzner Failover IP mover for Openstack is not running"
        return $OCF_NOT_RUNNING
    else
        pid=`cat $OCF_RESKEY_pid`
    fi

    ocf_run -warn kill -s 0 $pid
    rc=$?
    if [ $rc -eq 0 ]; then
        return $OCF_SUCCESS
    else
        ocf_log info "Old PID file found, but Hetzner Failover IP mover for Openstack is not running"
        return $OCF_NOT_RUNNING
    fi
}

hetzner_failover_ip_monitor() {
    local rc
    local token

    hetzner_failover_ip_status
    rc=$?

    # If status returned anything but success, return that immediately
    if [ $rc -ne $OCF_SUCCESS ]; then
        return $rc
    fi

    ocf_log debug "Hetzner Failover IP mover for Openstack monitor succeeded"
    return $OCF_SUCCESS
}

hetzner_failover_ip_start() {
    local rc

    hetzner_failover_ip_status
    rc=$?
    if [ $rc -eq $OCF_SUCCESS ]; then
        ocf_log info "Hetzner Failover IP mover for Openstack already running"
        return $OCF_SUCCESS
    fi

    # run the actual nova-volume daemon. Don't use ocf_run as we're sending the tool's output
    # straight to /dev/null anyway and using ocf_run would break stdout-redirection here.
    su ${OCF_RESKEY_user} -s /bin/sh -c "${OCF_RESKEY_binary}"' >> /dev/null 2>&1 & echo $!' > $OCF_RESKEY_pid

    # Spin waiting for the server to come up.
    # Let the CRM/LRM time us out if required
	sleep 1
    while true; do
    hetzner_failover_ip_monitor
    rc=$?
    [ $rc -eq $OCF_SUCCESS ] && break
    if [ $rc -ne $OCF_NOT_RUNNING ]; then
        ocf_log err "Hetzner Failover IP mover for Openstack start failed"
        exit $OCF_ERR_GENERIC
    fi
    sleep 1
    done

    ocf_log info "Hetzner Failover IP mover for Openstack started"
    return $OCF_SUCCESS
}

hetzner_failover_ip_stop() {
    local rc
    local pid

    hetzner_failover_ip_status
    rc=$?
    if [ $rc -eq $OCF_NOT_RUNNING ]; then
        ocf_log info "Hetzner Failover IP mover for Openstack already stopped"
        return $OCF_SUCCESS
    fi

    # Try SIGTERM
    pid=`cat $OCF_RESKEY_pid`
    ocf_run kill -s TERM $pid
    rc=$?
    if [ $rc -ne 0 ]; then
        ocf_log err "Hetzner Failover IP mover for Openstack couldn't be stopped"
        exit $OCF_ERR_GENERIC
    fi

    # stop waiting
    shutdown_timeout=15
    if [ -n "$OCF_RESKEY_CRM_meta_timeout" ]; then
        shutdown_timeout=$((($OCF_RESKEY_CRM_meta_timeout/1000)-5))
    fi
    count=0
    while [ $count -lt $shutdown_timeout ]; do
        hetzner_failover_ip_status
        rc=$?
        if [ $rc -eq $OCF_NOT_RUNNING ]; then
            break
        fi
        count=`expr $count + 1`
        sleep 1
        ocf_log debug "Hetzner Failover IP mover for Openstack still hasn't stopped yet. Waiting ..."
    done

    hetzner_failover_ip_status
    rc=$?
    if [ $rc -ne $OCF_NOT_RUNNING ]; then
        # SIGTERM didn't help either, try SIGKILL
        ocf_log info "Hetzner Failover IP mover for Openstack failed to stop after ${shutdown_timeout}s \
          using SIGTERM. Trying SIGKILL ..."
        ocf_run kill -s KILL $pid
    fi

    ocf_log info "Hetzner Failover IP mover for Openstack stopped"

    rm -f $OCF_RESKEY_pid

    return $OCF_SUCCESS
}

#######################################################################

case "$1" in
  meta-data)    meta_data
                exit $OCF_SUCCESS;;
  usage|help)   usage
                exit $OCF_SUCCESS;;
esac

# Anything except meta-data and help must pass validation
hetzner_failover_ip_validate || exit $?

# What kind of method was invoked?
case "$1" in
  start)        hetzner_failover_ip_start;;
  stop)         hetzner_failover_ip_stop;;
  status)       hetzner_failover_ip_status;;
  monitor)      hetzner_failover_ip_monitor;;
  validate-all) ;;
  *)            usage
                exit $OCF_ERR_UNIMPLEMENTED;;
esac